apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - name: iris
        image: us-central1-docker.pkg.dev/gentle-waters-459210-d0/iris/iris:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: iris
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
