apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - name: iris
        image: us-central1-docker.pkg.dev/gentle-waters-459210-d0/iris/iris:latest
        ports:
        - containerPort: 5000
        # Resource limits and health checks
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Liveness and readiness probes
        livenessProbe:
          httpGet:
            path: /health  
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health  
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: iris
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer